linters:
    Indentation:
        enabled: false

    PropertySortOrder:
        enabled: false

    IdSelector:
        enabled: false

    NameFormat:
        enabled: false

    SelectorFormat:
        enabled: false
